# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
Movie.create(title: "Solar Storm 1", overview: "In a dystopian future, a rebel challenges a powerful regime.", poster_url: "https://image.tmdb.org/t/p/original/sample1.jpg", rating: 7.4)
Movie.create(title: "Twilight Siege 5", overview: "In a dystopian future, a rebel challenges a powerful regime.", poster_url: "https://image.tmdb.org/t/p/original/sample3.jpg", rating: 7.4)
Movie.create(title: "Frozen Empire 4", overview: "In a dystopian future, a rebel challenges a powerful regime.", poster_url: "https://image.tmdb.org/t/p/original/sample5.jpg", rating: 7.6)
Movie.create(title: "Broken Truth 2", overview: "A mysterious force threatens Earth as a scientist races against time.", poster_url: "https://image.tmdb.org/t/p/original/sample1.jpg", rating: 6.6)
Movie.create(title: "Frozen Empire 3", overview: "A detective uncovers a dark conspiracy in the heart of the city.", poster_url: "https://image.tmdb.org/t/p/original/sample5.jpg", rating: 8.4)
Movie.create(title: "Phantom Signal 5", overview: "Two strangers' lives collide in an unexpected twist of fate.", poster_url: "https://image.tmdb.org/t/p/original/sample5.jpg", rating: 6.8)
Movie.create(title: "Beyond the Stars 2", overview: "A mysterious force threatens Earth as a scientist races against time.", poster_url: "https://image.tmdb.org/t/p/original/sample1.jpg", rating: 5.4)
Movie.create(title: "The Last Horizon 5", overview: "In a dystopian future, a rebel challenges a powerful regime.", poster_url: "https://image.tmdb.org/t/p/original/sample5.jpg", rating: 6.8)
Movie.create(title: "Rise of the Fallen 5", overview: "As war looms, an unlikely hero must rise to unite divided nations.", poster_url: "https://image.tmdb.org/t/p/original/sample1.jpg", rating: 7.3)
Movie.create(title: "Ashes of Tomorrow 3", overview: "A mysterious force threatens Earth as a scientist races against time.", poster_url: "https://image.tmdb.org/t/p/original/sample4.jpg", rating: 8.3)
Movie.create(title: "The Silent Code 2", overview: "Two strangers' lives collide in an unexpected twist of fate.", poster_url: "https://image.tmdb.org/t/p/original/sample3.jpg", rating: 8.7)
Movie.create(title: "Broken Truth 5", overview: "A detective uncovers a dark conspiracy in the heart of the city.", poster_url: "https://image.tmdb.org/t/p/original/sample3.jpg", rating: 6.8)
Movie.create(title: "The Silent Code 2", overview: "Two strangers' lives collide in an unexpected twist of fate.", poster_url: "https://image.tmdb.org/t/p/original/sample5.jpg", rating: 8.4)
Movie.create(title: "Velvet Cage 3", overview: "As war looms, an unlikely hero must rise to unite divided nations.", poster_url: "https://image.tmdb.org/t/p/original/sample4.jpg", rating: 6.7)
Movie.create(title: "Steel Heart 2", overview: "In a dystopian future, a rebel challenges a powerful regime.", poster_url: "https://image.tmdb.org/t/p/original/sample3.jpg", rating: 8.2)
Movie.create(title: "Broken Truth 2", overview: "A mysterious force threatens Earth as a scientist races against time.", poster_url: "https://image.tmdb.org/t/p/original/sample4.jpg", rating: 5.5)
Movie.create(title: "Solar Storm 3", overview: "As war looms, an unlikely hero must rise to unite divided nations.", poster_url: "https://image.tmdb.org/t/p/original/sample2.jpg", rating: 5.4)
Movie.create(title: "Velvet Cage 2", overview: "A detective uncovers a dark conspiracy in the heart of the city.", poster_url: "https://image.tmdb.org/t/p/original/sample1.jpg", rating: 6.2)
Movie.create(title: "Midnight Legacy 3", overview: "In a dystopian future, a rebel challenges a powerful regime.", poster_url: "https://image.tmdb.org/t/p/original/sample4.jpg", rating: 5.1)
Movie.create(title: "Fading Echo 2", overview: "As war looms, an unlikely hero must rise to unite divided nations.", poster_url: "https://image.tmdb.org/t/p/original/sample5.jpg", rating: 7.4)
Movie.create(title: "Solar Storm 5", overview: "As war looms, an unlikely hero must rise to unite divided nations.", poster_url: "https://image.tmdb.org/t/p/original/sample1.jpg", rating: 7.1)
Movie.create(title: "City of Lies 2", overview: "In a dystopian future, a rebel challenges a powerful regime.", poster_url: "https://image.tmdb.org/t/p/original/sample5.jpg", rating: 5.1)
Movie.create(title: "Fading Echo 2", overview: "In a dystopian future, a rebel challenges a powerful regime.", poster_url: "https://image.tmdb.org/t/p/original/sample1.jpg", rating: 8.8)
Movie.create(title: "Beyond the Stars 1", overview: "A detective uncovers a dark conspiracy in the heart of the city.", poster_url: "https://image.tmdb.org/t/p/original/sample2.jpg", rating: 6.5)
Movie.create(title: "Neon Dreams 1", overview: "As war looms, an unlikely hero must rise to unite divided nations.", poster_url: "https://image.tmdb.org/t/p/original/sample5.jpg", rating: 7.7)
Movie.create(title: "Frozen Empire 3", overview: "In a dystopian future, a rebel challenges a powerful regime.", poster_url: "https://image.tmdb.org/t/p/original/sample5.jpg", rating: 6.0)
Movie.create(title: "Velvet Cage 2", overview: "In a dystopian future, a rebel challenges a powerful regime.", poster_url: "https://image.tmdb.org/t/p/original/sample5.jpg", rating: 8.1)
Movie.create(title: "Frozen Empire 3", overview: "As war looms, an unlikely hero must rise to unite divided nations.", poster_url: "https://image.tmdb.org/t/p/original/sample2.jpg", rating: 5.3)
Movie.create(title: "Twilight Siege 4", overview: "As war looms, an unlikely hero must rise to unite divided nations.", poster_url: "https://image.tmdb.org/t/p/original/sample2.jpg", rating: 5.7)
Movie.create(title: "Frozen Empire 5", overview: "Two strangers' lives collide in an unexpected twist of fate.", poster_url: "https://image.tmdb.org/t/p/original/sample3.jpg", rating: 7.6)
Movie.create(title: "Whispers in the Wind 5", overview: "Two strangers' lives collide in an unexpected twist of fate.", poster_url: "https://image.tmdb.org/t/p/original/sample5.jpg", rating: 6.8)
Movie.create(title: "Rise of the Fallen 2", overview: "A mysterious force threatens Earth as a scientist races against time.", poster_url: "https://image.tmdb.org/t/p/original/sample2.jpg", rating: 5.9)
Movie.create(title: "Steel Heart 2", overview: "Two strangers' lives collide in an unexpected twist of fate.", poster_url: "https://image.tmdb.org/t/p/original/sample3.jpg", rating: 8.6)
Movie.create(title: "Crimson Shadows 3", overview: "As war looms, an unlikely hero must rise to unite divided nations.", poster_url: "https://image.tmdb.org/t/p/original/sample4.jpg", rating: 8.3)
Movie.create(title: "Fading Echo 3", overview: "As war looms, an unlikely hero must rise to unite divided nations.", poster_url: "https://image.tmdb.org/t/p/original/sample3.jpg", rating: 6.1)
Movie.create(title: "Solar Storm 1", overview: "A detective uncovers a dark conspiracy in the heart of the city.", poster_url: "https://image.tmdb.org/t/p/original/sample2.jpg", rating: 6.3)
Movie.create(title: "City of Lies 4", overview: "A detective uncovers a dark conspiracy in the heart of the city.", poster_url: "https://image.tmdb.org/t/p/original/sample3.jpg", rating: 5.5)
Movie.create(title: "Broken Truth 4", overview: "Two strangers' lives collide in an unexpected twist of fate.", poster_url: "https://image.tmdb.org/t/p/original/sample4.jpg", rating: 6.7)
Movie.create(title: "Twilight Siege 5", overview: "A mysterious force threatens Earth as a scientist races against time.", poster_url: "https://image.tmdb.org/t/p/original/sample1.jpg", rating: 6.0)
Movie.create(title: "City of Lies 4", overview: "In a dystopian future, a rebel challenges a powerful regime.", poster_url: "https://image.tmdb.org/t/p/original/sample2.jpg", rating: 7.0)
Movie.create(title: "Frozen Empire 3", overview: "As war looms, an unlikely hero must rise to unite divided nations.", poster_url: "https://image.tmdb.org/t/p/original/sample1.jpg", rating: 6.0)
Movie.create(title: "Neon Dreams 2", overview: "A detective uncovers a dark conspiracy in the heart of the city.", poster_url: "https://image.tmdb.org/t/p/original/sample2.jpg", rating: 8.8)
Movie.create(title: "Frozen Empire 2", overview: "A detective uncovers a dark conspiracy in the heart of the city.", poster_url: "https://image.tmdb.org/t/p/original/sample2.jpg", rating: 5.7)
Movie.create(title: "Whispers in the Wind 4", overview: "A mysterious force threatens Earth as a scientist races against time.", poster_url: "https://image.tmdb.org/t/p/original/sample5.jpg", rating: 5.5)
Movie.create(title: "Midnight Legacy 2", overview: "A mysterious force threatens Earth as a scientist races against time.", poster_url: "https://image.tmdb.org/t/p/original/sample4.jpg", rating: 7.3)
Movie.create(title: "Ashes of Tomorrow 3", overview: "Two strangers' lives collide in an unexpected twist of fate.", poster_url: "https://image.tmdb.org/t/p/original/sample4.jpg", rating: 8.1)
Movie.create(title: "City of Lies 2", overview: "A mysterious force threatens Earth as a scientist races against time.", poster_url: "https://image.tmdb.org/t/p/original/sample1.jpg", rating: 7.8)
Movie.create(title: "Midnight Legacy 5", overview: "As war looms, an unlikely hero must rise to unite divided nations.", poster_url: "https://image.tmdb.org/t/p/original/sample5.jpg", rating: 8.8)
Movie.create(title: "Dreamcatcher 4", overview: "In a dystopian future, a rebel challenges a powerful regime.", poster_url: "https://image.tmdb.org/t/p/original/sample1.jpg", rating: 5.5)
Movie.create(title: "City of Lies 2", overview: "As war looms, an unlikely hero must rise to unite divided nations.", poster_url: "https://image.tmdb.org/t/p/original/sample5.jpg", rating: 9.0)
